environment:  
  pms: 100
  vms: 250
  var: 0.01
  service_length: 100
  arrival_rate: 1.818 # 100% system load: pms / distribution expectation / service length 
  training_steps: 1000
  eval_steps: 10000
  seed: 0
  reward_function: wr
  cap_target_util: true
  sequence: "uniform"
  beta: 0.5
agents: 
  ppo: 
      episodes: 2000
      hidden_size: 512
      batch_size: 100
      minibatch_size: 25
      migration_ratio: 1
      device: cpu 
  caviglione: 
      episodes: 2000
      hidden_size: 512
      device: cpu
  convex:
      migration_penalty: 1
      W: 30
