environment:  
  pms: 100
  vms: 300
  service_length: 1000
  arrival_rate: 1.8182 # 100% system load: pms / distribution expectation / service length 
  training_steps: 10000
  eval_steps: 100000
  seed: 0
  reward_function: kl
  cap_target_util: true
  sequence: "uniform"
  beta: 0.5
  allow_null_action: true
agents: 
  ppo: 
      episodes: 100
      hidden_size: 512
      masked: true
      device: cpu
      batch_size: 100
      minibatch_size: 25
  caviglione: 
      episodes: 100
      hidden_size: 512
      device: cpu
  convex:
      migration_penalty: 1
      W: 30