environment:  
  pms: 100
  vms: 250
  var: 0.01
  service_length: 500
  arrival_rate: 0.364 # 100% system load: pms / distribution expectation / service length 
  training_steps: 5000
  eval_steps: 10000
  seed: 0
  reward_function: wr
  cap_target_util: true
  sequence: "uniform"
  beta: 0.5
agents: 
  ppo: 
      episodes: 400
      hidden_size: 512
      migration_ratio: 1
  caviglione: 
      episodes: 400
      hidden_size: 512
      device: cpu
  convex:
      migration_penalty: 1
      W: 30
