environment:  
  pms: 10
  vms: 30
  var: 0.01
  service_length: 100
  arrival_rate: 0.182 # 100% system load: pms / distribution expectation / service rate 
  training_steps: 500
  eval_steps: 100000
  seed: 0
  reward_function: waiting_ratio
  cap_target_util: true
  sequence: "uniform"
  beta: 0.5
agents: 
  ppo: 
      episodes: 2000
      hidden_size: 128
      device: cpu 
  ppolstm: 
      episodes: 2000 
      hidden_size: 128
      device: cpu
  rainbow: 
      episodes: 2000
      hidden_size: 128
  caviglione: 
      episodes: 2000
      hidden_size: 128
  convexrank:
      migration_penalty: 1
  convexrankall:
      migration_penalty: 1
      W: 30