environment:  
  pms: 10
  vms: 30
  var: 0.01
  service_length: 100
  arrival_rate: 0.182 # 100% system load: pms / distribution expectation / service length 
  training_steps: 1000
  eval_steps: 10000
  seed: 0
  reward_function: ut
  cap_target_util: true
  sequence: "uniform"
  beta: 0.5
agents: 
  ppo: 
      episodes: 2000
      hidden_size: 64
      migration_ratio: 0.1
      masked: True
  caviglione: 
      episodes: 1000
      hidden_size: 64
      device: cpu
  convex:
      migration_penalty: 1
      W: 30