environment:  
  pms: 100
  vms: 250
  var: 0.01
  service_length: 1000
  arrival_rate: 0.182 # 100% system load: pms / distribution expectation / service length 
  training_steps: 10000
  eval_steps: 100000
  seed: 0
  reward_function: waiting_ratio
  cap_target_util: true
  sequence: "uniform"
  beta: 0.5
agents: 
  ppo: 
      episodes: 100
      hidden_size: 256
      batch_size: 100
      minibatch_size: 25
      migration_discount: 0.25
      device: cpu 
  caviglione: 
      episodes: 100
      hidden_size: 256
      device: cpu
  convex:
      migration_penalty: 1
      W: 30
